[package]
name = "netstack3-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "netstack3_core"

[features]
instrumented = []
testutils = ["instrumented"]
benchmark = ["netstack3_base/benchmark", "netstack3_udp/benchmark", "dep:criterion"]

[dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true, optional = true }
derivative = { workspace = true, features = ["use_core"] }
lock_order = { package = "lock-order", path = "lock-order" }
log = { workspace = true }
net_types = { package = "net-types", path = "../../libs/net-types" }
netstack3_base = { package = "netstack3-base", path = "base" }
netstack3_datagram = { package = "netstack3-datagram", path = "datagram" }
netstack3_device = { package = "netstack3-device", path = "device" }
netstack3_filter = { package = "netstack3-filter", path = "filter" }
netstack3_hashmap = { package = "netstack3-hashmap", path = "hashmap" }
netstack3_icmp_echo = { package = "netstack3-icmp-echo", path = "icmp_echo" }
netstack3_ip = { package = "netstack3-ip", path = "ip" }
netstack3_macros = { package = "netstack3-macros", path = "macros" }
netstack3_sync = { package = "netstack3-sync", path = "sync" }
netstack3_tcp = { package = "netstack3-tcp", path = "tcp" }
netstack3_trace = { package = "netstack3-trace", path = "trace" }
netstack3_udp = { package = "netstack3-udp", path = "udp" }
packet = { path = "../../libs/packet" }
packet_formats = { package = "packet_formats", path = "../../libs/packet-formats" }
zerocopy = { workspace = true, features = ["derive"] }

[[bench]]
name = "netstack3"
harness = false
required-features = ["benchmark"]
