[package]
name = "netstack3-base"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "netstack3_base"

[features]
testutils = ["instrumented", "netstack3_sync/testutils", "dep:net_declare", "dep:teststd", "dep:assert_matches", "dep:rand_xorshift"]
instrumented = ["netstack3_sync/instrumented"]
benchmark = []

[dependencies]
arc-swap = { workspace = true }
arrayvec = { workspace = true }
assert_matches = { workspace = true, optional = true }
bitflags = { workspace = true }
derivative = { workspace = true, features = ["use_core"] }
diagnostics_traits = { package = "diagnostics-traits", path = "../../../libs/diagnostics-traits" }
either = { workspace = true }
explicit = { path = "../../../libs/explicit" }
log = { workspace = true }
net_declare = { package = "net-declare", path = "../../../libs/net-declare", optional = true }
net_types = { package = "net-types", path = "../../../libs/net-types" }
netstack3_hashmap = { package = "netstack3-hashmap", path = "../hashmap" }
netstack3_sync = { package = "netstack3-sync", path = "../sync" }
packet = { path = "../../../libs/packet" }
packet_formats = { package = "packet_formats", path = "../../../libs/packet-formats" }
rand = { workspace = true }
rand_xorshift = { workspace = true, optional = true }
smallvec = { workspace = true }
static_assertions = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
teststd = { path = "../teststd", optional = true }
thiserror = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }
