[package]
name = "netstack3-benchmarks"
edition.workspace = true
version.workspace = true
license.workspace = true
publish = false

[dependencies]
criterion = { workspace = true }
netstack3_base = { package = "netstack3-base", path = "../core/base", features = ["testutils"] }
netstack3_sync = { package = "netstack3-sync", path = "../core/sync", features = ["single-threaded"] }
netstack3_udp = { package = "netstack3-udp", path = "../core/udp", features = ["bench-support"] }

[lib]
name = "netstack3_benchmarks"
path = "src/lib.rs"

[[bench]]
name = "netstack3"
harness = false

[[bench]]
name = "udp_receive_throughput"
harness = false

[[example]]
name = "profile_udp_receive"
