[package]
name = "netstack3-ip"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "netstack3_ip"

[features]
testutils = ["instrumented"]
instrumented = []

[dependencies]
arrayvec = { workspace = true }
assert_matches = { workspace = true }
derivative = { workspace = true, features = ["use_core"] }
diagnostics_traits = { package = "diagnostics-traits", path = "../../../libs/diagnostics-traits" }
either = { workspace = true }
explicit = { path = "../../../libs/explicit" }
hmac = { workspace = true }
lock_order = { package = "lock-order", path = "../lock-order" }
log = { workspace = true }
lru-cache = { workspace = true }
net_declare = { package = "net-declare", path = "../../../libs/net-declare" }
net_types = { package = "net-types", path = "../../../libs/net-types" }
netstack3_base = { package = "netstack3-base", path = "../base" }
netstack3_filter = { package = "netstack3-filter", path = "../filter" }
netstack3_hashmap = { package = "netstack3-hashmap", path = "../hashmap" }
netstack3_macros = { package = "netstack3-macros", path = "../macros" }
netstack3_trace = { package = "netstack3-trace", path = "../trace" }
packet = { path = "../../../libs/packet" }
packet_formats = { package = "packet_formats", path = "../../../libs/packet-formats" }
rand = { workspace = true }
ref-cast = { workspace = true }
sha2 = { workspace = true }
static_assertions = { workspace = true }
thiserror = { workspace = true }
zerocopy = { workspace = true, features = ["derive"] }
